#!/bin/bash

target="$1"

if [ -z "$target" ]; then
    echo "Usage: $0 <target>"
    exit 1
fi

#create output file from target with curreht date as suffix
output="${target}_$(date +%Y-%m-%d).sql"

echo "Dumping database to $output..."

#Backup script for the server
docker compose up backup --build --remove-orphans
docker compose run --rm backup sh -c 'PGPASSFILE=.pgpass pg_dump -U postgres -h postgres yt_rec_graph' > "$output"
