#!/usr/bin/env bash

server=$1
password=$2
concurrency="${3:-4}"

echo "Running script with bash:"
bash --version

if [ -z "$server" ]; then
  echo "Usage: $0 <server> <password> [concurrency=4]"
  exit 1
fi

if [ -z "$password" ]; then
  echo "Usage: $0 <server> <password> [concurrency=4]"
  exit 1
fi

echo "Building app to run client..."

docker compose build --remove-orphans client
docker compose run -it --rm --service-ports -e LOG=show client bash docker-client "$server" "$password" "$concurrency"
