#!/usr/bin/env bash

server=$1
password=$2
concurrency="${3:-4}"

echo "Running script with bash:"
bash --version

if [ -z "$server" ]; then
  echo "Usage: $0 <server> <password> [concurrency=4]"
  exit 1
fi

if [ -z "$password" ]; then
  echo "Usage: $0 <server> <password> [concurrency=4]"
  exit 1
fi

echo "Running $concurrency clients against $server"

for i in $(seq 1 "$concurrency"); do
  echo "Running client $i"
  yarn pm2 start -f src/bin/client.ts -- "$server" "$password"
done

while true
do
  clear
  yarn pm2 ps
  sleep 5

  yarn pm2 logs --lines=15
  sleep 5
done
