#!/usr/bin/env bash

server=$1
password=$2
concurrency="${3:-4}"

echo "Running script with bash:"
bash --version

if [ -z "$server" ]; then
  echo "Usage: $0 <server> <password> [concurrency=4]"
  exit 1
fi

if [ -z "$password" ]; then
  echo "Usage: $0 <server> <password> [concurrency=4]"
  exit 1
fi

echo "Running max $concurrency clients against $server"

# ln -s "$(which ts-node)" /usr/local/lib/node_modules/pm2/node_modules/.bin/

export SERVER="$server"
export SERVER_PASSWORD="$password"

pm2 start client.config.js -i "$concurrency"

pm2 logs --raw
