version: "3.9"

services:
  app:
    image: yt-map-app-test
    build: .
    depends_on:
    - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres-test
      POSTGRES_PASSWORD: hello-test
      POSTGRES_DB: yt_rec_graph-test
    ports:
      - "5432:5432"
    volumes:
      - yt_graph-test:/var/lib/postgresql/data
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
    - postgres
volumes:
  yt_graph-test:
    driver: local
