version: "4"
services:
  client:
    build: ./docker/client

  server:
    build: ./docker/server
    ports:
      - "38472:38472"
    depends_on:
      - postgres

  server-test:
    build: .
    ports:
      - "38478:38478"
    depends_on:
      - postgres-test
    environment:
      - NODE_ENV=test-docker
      - LOG=show
    command: yarn server secret

  tester:
    build:
      context: .
      dockerfile: ./docker/tester/Dockerfile
    depends_on:
      - server-test
    environment:
      - NODE_ENV=test-docker
      - LOG=show

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: yt_rec_graph
    ports:
      - "5432:5432"
    volumes:
      - yt_graph:/var/lib/postgresql/data
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
      - ./my-pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

  postgres-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test-yt_rec_graph
    ports:
      - "5433:5432"
    volumes:
      - test-yt_rec_graph:/var/lib/postgresql/data
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
      - ./my-pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

  backup:
    build: ./backuper
    depends_on:
      - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - postgres-test

volumes:
  yt_graph:
    driver: local
  test-yt_rec_graph:
    driver: local
