version: "3.9"
services:
  client:
    build: .
    image: djfm/ts-yt-map:latest
    network_mode: host

  server:
    image: djfm/ts-yt-map:latest
    ports:
     - "38472:38472"
    depends_on:
      - postgres

  server-integration:
    image: fm/yt_rec_graph:latest
    ports:
      - "38479:38479"
    depends_on:
      - postgres-integration

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: yt_rec_graph
    ports:
      - "5432:5432"
    volumes:
      - yt_graph:/var/lib/postgresql/data

  postgres-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test-yt_rec_graph
    ports:
      - "5433:5432"
    volumes:
      - test-yt_rec_graph:/var/lib/postgresql/data

  postgres-integration:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: integration
      POSTGRES_PASSWORD: integration
      POSTGRES_DB: integration-yt_rec_graph
    ports:
      - "5435:5432"
    volumes:
      - integration-yt_rec_graph:/var/lib/postgresql/data

  backup:
    build: ./backuper
    depends_on:
      - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  yt_graph:
    driver: local
  test-yt_rec_graph:
    driver: local
  integration-yt_rec_graph:
    driver: local
