#!/usr/bin/env bash

password="$1"

if [ -z "$password" ]; then
    echo "Usage: $0 <password>"
    exit 1
fi

export PATH=/root/yt_rec_graph/node_modules/.bin/pm2:$PATH
SERVER_PASSWORD="$password" node_modules/.bin/pm2 start ecosystem.config.js

node_modules/.bin/pm2 logs --raw
