#!/usr/bin/env bash

server=$1
password=$2
projectId=$3
concurrency=$4

echo "Running script with bash:"
bash --version

echo "Running max $concurrency clients against $server"

# ln -s "$(which ts-node)" /usr/local/lib/node_modules/pm2/node_modules/.bin/

export SERVER="$server"
export SERVER_PASSWORD="$password"
export CONCURRENCY="$concurrency"
export PROJECT_ID="$projectId"

pm2 start client.config.js

pm2 logs
