version: "3.9"
services:
  server:
    build: .
    ports:
      - "38472:38472"
    depends_on:
      - postgres
  server-test:
    build: .
    ports:
      - "38478:38472"
    depends_on:
      - postgres-test
  client:
    build: .
  client-test:
    build: .
    depends_on:
      - postgres-test
  postgres-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test-yt_rec_graph
    ports:
      - "5433:5432"
    volumes:
      - yt_graph-test:/var/lib/postgresql/data
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: yt_rec_graph
    ports:
      - "5432:5432"
    volumes:
      - yt_graph:/var/lib/postgresql/data
  backup:
    build: ./backuper
    depends_on:
      - postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  yt_graph:
    driver: local
  yt_graph-test:
    driver: local
