#!/usr/bin/env bash

password=$1

if [ -z "$password" ]; then
    echo "Usage: $0 <password>"
    exit 1
fi

docker compose up --build --remove-orphans -d
docker compose run --service-ports --rm -e NODE_ENV=production-docker -e LOG=show app bash docker-server "$password"