#!/bin/bash

sudo apt-get remove docker docker-engine docker.io containerd runc
sudo apt-get update
sudo apt-get install \
  ca-certificates \
  curl \
  gnupg \
  lsb-release
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-compose -y

sudo usermod -aG docker "$USER"
newgrp docker

sudo apt-get install -y dbus-user-session uidmap htop

sudo systemctl disable --now docker.service docker.socket
sudo systemctl stop --now docker.service docker.socket
dockerd-rootless-setuptool.sh install
echo "export PATH=/usr/bin:$PATH" >> ~/.bashrc
echo "export DOCKER_HOST=unix:///run/user/1000/docker.sock" >> ~/.bashrc
bash
systemctl --user start docker
systemctl --user enable docker
sudo loginctl enable-linger "$(whoami)"

sudo apt install git tmux -y
git clone https://github.com/djfm/ts-yt-map.git

ssh-copy-id djfm@socks.fmdj.fr

# Run in tmux:
# cd ts-yt-map && ./client https://yt.fmdj.fr tralala 16