#!/usr/bin/env bash

docker compose build client-test
docker compose run --service-ports --rm -e NODE_ENV=test-docker -e LOG=show server-test yarn server secret
docker compose run --service-ports --rm -e NODE_ENV=test-docker -e LOG=show client-test bash do-run-tests
