seed_video: https://www.youtube.com/watch?v=x-QcbOphxYs
client_name: unnamed client
host: server
port: 38472
db:
  host: postgres
  port: 5432
  username: postgres
  password: hello
  database: yt_rec_graph
