name: CI
on: [push, pull_request]
jobs:
  ci:
      name: Continuous Integration
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Install docker
          run: bash setup-ubuntu-docker-root
        - Install node
          run: sudo snap install node --classic --channel=18/stable
        - name: Run the tests
          run: ./test
