name: CI
on: [push, pull_request]
jobs:
  ci:
      name: Continuous Integration
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Run the tests with Docker
          run: docker compose up --build --remove-orphans -d && docker compose run --rm -e NODE_ENV=test-docker -e LOG=show app yarn test
