name: CI
on: [push]
jobs:
  Run-Tests:
    runs-on: docker
    steps:
      - name: Check out repository code
      uses: actions/checkout@v3
      - run: docker compose up --build --remove-orphans -d && docker compose run --rm -e NODE_ENV=test-docker -e LOG=show app yarn test
