name: CI
on: [push]
jobs:
  ci:
      name: Continuous Integration
      runs-on: docker:latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Install docker
          uses: KengoTODA/actions-setup-docker-compose@main
          with:
            version: '1.29.2'
        - name: Run the tests with Docker
          run: docker compose up --build --remove-orphans -d && docker compose run --rm -e NODE_ENV=test-docker -e LOG=show app yarn test
