name: CI
on: [push, pull_request]
jobs:
  ci:
      name: Continuous Integration
      runs-on: centminmod/docker-ubuntu-vnc-desktop
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Start the test database container
          run: docker compose up -d postgres-test
        - name: Run the tests
          run: ./test
